---
charts:
  - name: qubership-colly
    chart_file: charts/qubership-colly/Chart.yaml
    values_file: charts/qubership-colly/values.yaml
    image:
      - ghcr.io/netcracker/envgene-inventory-service:${release}
      - ghcr.io/netcracker/environment-operational-service:${release}
      - ghcr.io/netcracker/ui-service:${release}
